# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cutBmh8D6XgTumDH9G0Bzy6J11i4cHTp
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

data = pd.read_csv('LR.csv')

data.head()

data.drop('Unnamed:0',axis=1,inplace=True)
data.head()

sns.pairplot(data, x_vars=['TV','newspaper','radio'], y_vars='sales',kind='scatter')
plt.show()

